"""Quick check for the Task 2 architecture.

Run with:
    python check_architecture.py

This is not a training script. It is a lightweight smoke test: it checks that
the data generated by the HMM/Forward-Backward pipeline can pass through the
new neural architecture without shape errors, padding errors, or invalid losses.
"""

import torch

from architecture import (
    PAD_IDX,
    SequenceSummaryNetwork,
    create_bayesflow_components,
    masked_bce_loss,
    pad_sequences,
    pad_targets,
    prepare_bayesflow_batch,
    predict_alpha_probabilities,
)
from forward_backward import generate_dataset
from simulator import get_rng


def main() -> None:
    # Use a fixed seed so this check is reproducible. The generated sequences
    # and posteriors should be the same every time the script is run.
    rng = get_rng(0)

    # Generate a tiny batch of variable-length sequences. posteriors contains
    # the exact Forward-Backward target P(alpha | sequence) for every position.
    sequences, posteriors, _states = generate_dataset(
        n=8,
        rng=rng,
        min_len=10,
        max_len=30,
    )

    # Convert ragged Python lists into rectangular tensors:
    # padded_sequences: integer amino-acid ids plus PAD_IDX
    # mask: True at real amino-acid positions, False at padding positions
    # lengths: original sequence lengths before padding
    padded_sequences, mask, lengths = pad_sequences(sequences)

    # Pad the target posterior probabilities to the same batch shape. The loss
    # will use mask, so target values at padded positions are ignored.
    padded_targets = pad_targets(posteriors)

    # Build the network. These dimensions are intentionally small enough for a
    # quick check, but they still exercise the full architecture.
    model = SequenceSummaryNetwork(
        embedding_dim=32,
        hidden_dim=64,
        summary_dim=64,
        bidirectional=True,
    )

    # Run one forward pass. summary has one row per sequence; logits has one
    # value per sequence position.
    summary, logits = model(
        padded_sequences,
        mask=mask,
        lengths=lengths,
        return_position_logits=True,
    )

    # Compute the masked loss and convert logits to probabilities for
    # inspection. No optimizer step happens here.
    loss = masked_bce_loss(logits, padded_targets, mask)
    probs = predict_alpha_probabilities(logits, mask)

    # Also verify the BayesFlow-facing batch format. This does not require
    # BayesFlow to be installed: it only checks that our data can be represented
    # with the fixed names/shapes that a BayesFlow adapter would consume.
    bayesflow_batch = prepare_bayesflow_batch(
        sequences,
        posteriors=posteriors,
        summary_network=model,
    )
    bayesflow_data = bayesflow_batch.as_dict()

    # Shape checks: all per-position tensors should line up exactly with the
    # padded input. This catches most padding/masking bugs early.
    assert padded_sequences.shape == mask.shape
    assert padded_targets.shape == mask.shape
    assert logits.shape == mask.shape
    assert probs.shape == mask.shape

    # The summary vector should contain one fixed-size representation per
    # sequence in the batch.
    assert summary.shape == (len(sequences), 64)

    # Every non-real position in padded_sequences should contain the special
    # padding token, never an amino-acid id.
    assert torch.all(padded_sequences[~mask] == PAD_IDX)

    # A finite loss means the forward pass produced numerically valid values.
    assert torch.isfinite(loss)

    # BayesFlow-facing checks: the adapter will need named arrays with fixed
    # shapes, so make sure the names and dimensions are present.
    assert bayesflow_data["observables"].shape == padded_sequences.shape
    assert bayesflow_data["mask"].shape == mask.shape
    assert bayesflow_data["lengths"].shape == lengths.shape
    assert bayesflow_data["alpha_posteriors"].shape == padded_targets.shape
    assert bayesflow_data["sequence_summary"].shape == summary.shape

    # If BayesFlow is installed, check that the real adapter and coupling-flow
    # inference network can be instantiated. This is the configuration part of
    # the Bayesian/SBI workflow; fitting the workflow belongs to the training
    # pipeline, not this smoke test.
    bayesflow_status = "not installed"
    try:
        components = create_bayesflow_components()
    except ImportError:
        components = None
    if components is not None:
        bayesflow_status = (
            f"{type(components['adapter']).__name__} + "
            f"{type(components['inference_network']).__name__}"
        )

    # Print the important tensor shapes so the check doubles as a small demo of
    # what the architecture expects and returns.
    print("Architecture check passed.")
    print(f"batch size       : {len(sequences)}")
    print(f"max length       : {padded_sequences.shape[1]}")
    print(f"sequence tensor  : {tuple(padded_sequences.shape)}")
    print(f"mask tensor      : {tuple(mask.shape)}")
    print(f"target tensor    : {tuple(padded_targets.shape)}")
    print(f"summary tensor   : {tuple(summary.shape)}")
    print(f"logits tensor    : {tuple(logits.shape)}")
    print(f"prob tensor      : {tuple(probs.shape)}")
    print(f"BayesFlow keys   : {', '.join(sorted(bayesflow_data))}")
    print(f"BayesFlow config : {bayesflow_status}")
    print(f"initial loss     : {loss.item():.4f}")
    print("All shape and loss checks are OK.")


if __name__ == "__main__":
    main()
